import { describe, expect, test } from "bun:test";
import { expectedProductionSecrets } from "./check-production-secrets";

function interfaceBody(source: string, name: string): string {
  const match = source.match(new RegExp(`(?:export )?interface ${name} \\{([\\s\\S]*?)\\n\\}`));
  if (!match) throw new Error(`missing interface ${name}`);
  return match[1];
}

function expectEnvField(body: string, name: string): void {
  expect(body).toMatch(new RegExp(`(^|\\s)${name}\\??:`));
}

export function reviewedSecretNames(wrangler: string): string[] {
  const match = wrangler.match(/# secrets \(set via:[^\n]*\)\n([\s\S]*?)# end secrets/);
  if (!match) throw new Error("wrangler.toml must contain a bounded # secrets block");
  const end = wrangler.indexOf("# end secrets");
  if (/^# [A-Z][A-Z0-9_]+(?:\s|$)/m.test(wrangler.slice(end + "# end secrets".length))) {
    throw new Error("secret comment appears after # end secrets");
  }
  const names = [...match[1].matchAll(/^# ([A-Z][A-Z0-9_]+)(?:\s|$)/gm)].map((item) => item[1]);
  if (names.length === 0) throw new Error("bounded # secrets block must not be empty");
  return names;
}

describe("Worker environment provenance", () => {
  test("keeps generated bindings and reviewed secrets aligned with Wrangler", async () => {
    const [wrangler, generated, source] = await Promise.all([
      Bun.file("wrangler.toml").text(),
      Bun.file("worker-configuration.d.ts").text(),
      Bun.file("src/index.ts").text(),
    ]);
    expect(generated).toMatch(/^\/\* eslint-disable \*\/\n\/\/ Generated by Wrangler by running `wrangler types` \(hash: [a-f0-9]{32}\)/);
    expect(generated).toMatch(/^\/\/ Runtime types generated with workerd@/m);

    const bindings = [...wrangler.matchAll(/^binding = "([A-Z][A-Z0-9_]*)"$/gm)].map((match) => match[1]);
    const vars = [...wrangler.matchAll(/^([A-Z][A-Z0-9_]*) = "[^"]*"$/gm)].map((match) => match[1]);
    const secrets = reviewedSecretNames(wrangler);
    const generatedEnv = interfaceBody(generated, "__BaseEnv_Env");
    const runtimeEnv = interfaceBody(source, "Env");

    expect(new Set(bindings)).toEqual(new Set(["DB", "DISPATCHES"]));
    expect(
      new Set(expectedProductionSecrets),
      "scripts/check-production-secrets.ts and wrangler.toml must agree exactly",
    ).toEqual(new Set(secrets));
    for (const name of [...bindings, ...vars]) {
      expectEnvField(generatedEnv, name);
      expectEnvField(runtimeEnv, name);
    }
    for (const name of secrets) expectEnvField(runtimeEnv, name);
  });

  test("fails closed on a missing, empty, or overrun secrets sentinel", () => {
    expect(() => reviewedSecretNames("# secrets (set via: test)\n# TOKEN\n")).toThrow("bounded # secrets block");
    expect(() => reviewedSecretNames("# secrets (set via: test)\n# end secrets\n")).toThrow("must not be empty");
    expect(() => reviewedSecretNames("# secrets (set via: test)\n# TOKEN\n# end secrets\n# LATE_TOKEN\n"))
      .toThrow("appears after # end secrets");
  });
});
