import { describe, expect, test } from "bun:test";
import { expectedProductionSecrets } from "./check-production-secrets";

function interfaceBody(source: string, name: string): string {
  const match = source.match(new RegExp(`(?:export )?interface ${name} \\{([\\s\\S]*?)\\n\\}`));
  if (!match) throw new Error(`missing interface ${name}`);
  return match[1];
}

function expectEnvField(body: string, name: string): void {
  expect(body).toMatch(new RegExp(`(^|\\s)${name}\\??:`));
}

describe("Worker environment provenance", () => {
  test("keeps generated bindings and reviewed secrets aligned with Wrangler", async () => {
    const [wrangler, generated, source] = await Promise.all([
      Bun.file("wrangler.toml").text(),
      Bun.file("worker-configuration.d.ts").text(),
      Bun.file("src/index.ts").text(),
    ]);
    expect(generated).toMatch(/^\/\* eslint-disable \*\/\n\/\/ Generated by Wrangler by running `wrangler types` \(hash: [a-f0-9]{32}\)/);
    expect(generated).toMatch(/^\/\/ Runtime types generated with workerd@/m);

    const bindings = [...wrangler.matchAll(/^binding = "([A-Z][A-Z0-9_]*)"$/gm)].map((match) => match[1]);
    const vars = [...wrangler.matchAll(/^([A-Z][A-Z0-9_]*) = "[^"]*"$/gm)].map((match) => match[1]);
    const secretBlockMatch = wrangler.match(/# secrets \(set via:[^\n]*\)\n([\s\S]*?)# end secrets/);
    expect(secretBlockMatch, "wrangler.toml must contain a bounded # secrets block").not.toBeNull();
    const secretBlock = secretBlockMatch?.[1] ?? "";
    const secrets = [...secretBlock.matchAll(/^# ([A-Z][A-Z0-9_]+)(?:\s|$)/gm)].map((match) => match[1]);
    const generatedEnv = interfaceBody(generated, "__BaseEnv_Env");
    const runtimeEnv = interfaceBody(source, "Env");

    expect(new Set(bindings)).toEqual(new Set(["DB", "DISPATCHES"]));
    expect(secrets.length).toBeGreaterThan(0);
    expect(
      new Set(expectedProductionSecrets),
      "scripts/check-production-secrets.ts and wrangler.toml must agree exactly",
    ).toEqual(new Set(secrets));
    for (const name of [...bindings, ...vars]) {
      expectEnvField(generatedEnv, name);
      expectEnvField(runtimeEnv, name);
    }
    for (const name of secrets) expectEnvField(runtimeEnv, name);
  });
});
